mysql:
  ip: 127.0.0.1
  port: 3307

server:
  port: 8080

miss-you:
  api:
    package: com.yy.ymissyou.api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/missyou?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true #在控制台打印SQL




