spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto:create----每次运行该程序，没有表格会新建表格，表内有数据会清空
      #ddl-auto:create-drop----每次程序结束的时候会清空表
      #ddl-auto:validate----运行程序会校验数据与数据库的字段类型是否相同，不同会报错
      #ddl-auto: update 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新,注意：只能识别出增加的字段，比如修改字段名，修改字段类型或者删除一个字段都是不能够识别的。